{"name": "test_wrong_balance", "status": "broken", "statusDetails": {"message": "cardano_node_tests.utils.clusterlib.CLIError: An error occurred running a CLI command `cardano-cli shelley transaction build-raw --ttl 3187 --fee 200000 --out-file /tmp/pytest-of-martink/pytest-1/popen-gw7/test_transactions_py0/test_wrong_balance_201104_135320774_mynb_tx.body --tx-in 77df88f54059b9f19649e298d6645c4370cd4358583106340995f87da1358217#0 --tx-out addr_test1vrw2qjxyd4w5rtcqltkxta5vdevfgnm4ffvlsyvh7ywj79gfxu2dh+2800000 --tx-out addr_test1vpgpgpss8k2r53vus3m3d3j9jvmjc9a8ve836h7pdaff6rc69n7v6+18446744073709551616`: \ncardano-cli: out of bounds : 18446744073709551616\nCallStack (from HasCallStack):\n  error, called at src/Shelley/Spec/Ledger/Coin.hs:85:7 in shelley-spec-ledger-0.1.0.0-HfhISpN74MdH4YWGDs1y5I:Shelley.Spec.Ledger.Coin", "trace": "self = <cardano_node_tests.tests.test_transactions.TestNotBalanced object at 0x7fbf1a84e1c0>, cluster = <cardano_node_tests.utils.clusterlib.ClusterLib object at 0x7fbf202d73d0>\npayment_addrs = [AddressRecord(address='addr_test1vpgpgpss8k2r53vus3m3d3j9jvmjc9a8ve836h7pdaff6rc69n7v6', vkey_file=PosixPath('addr_no...fvlsyvh7ywj79gfxu2dh', vkey_file=PosixPath('addr_not_balanced1.vkey'), skey_file=PosixPath('addr_not_balanced1.skey'))]\ntemp_dir = PosixPath('/tmp/pytest-of-martink/pytest-1/popen-gw7/test_transactions_py0')\n\n>   ???\n\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/test_transactions.py:485: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/test_transactions.py:525: in test_wrong_balance\n    cluster.build_raw_tx_bare(\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/clusterlib.py:925: in build_raw_tx_bare\n    self.cli(\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/clusterlib.py:261: in cli\n    return self.cli_base(cmd)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <cardano_node_tests.utils.clusterlib.ClusterLib object at 0x7fbf202d73d0>, cli_args = ['cardano-cli', 'shelley', 'transaction', 'build-raw', '--ttl', '3187', ...]\n\n    def cli_base(self, cli_args: List[str]) -> CLIOut:\n        \"\"\"Run command.\"\"\"\n        cmd_str = \" \".join(cli_args)\n        LOGGER.debug(\"Running `%s`\", cmd_str)\n    \n        # re-run the command when running into\n        # Network.Socket.connect: <socket: X>: resource exhausted (Resource temporarily unavailable)\n        for __ in range(3):\n            p = subprocess.Popen(cli_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n            stdout, stderr = p.communicate()\n    \n            if p.returncode == 0:\n                break\n    \n            stderr_dec = stderr.decode()\n            err_msg = f\"An error occurred running a CLI command `{cmd_str}`: {stderr_dec}\"\n            if \"resource exhausted\" in stderr_dec:\n                LOGGER.error(err_msg)\n                time.sleep(1)\n                continue\n>           raise CLIError(err_msg)\nE           cardano_node_tests.utils.clusterlib.CLIError: An error occurred running a CLI command `cardano-cli shelley transaction build-raw --ttl 3187 --fee 200000 --out-file /tmp/pytest-of-martink/pytest-1/popen-gw7/test_transactions_py0/test_wrong_balance_201104_135320774_mynb_tx.body --tx-in 77df88f54059b9f19649e298d6645c4370cd4358583106340995f87da1358217#0 --tx-out addr_test1vrw2qjxyd4w5rtcqltkxta5vdevfgnm4ffvlsyvh7ywj79gfxu2dh+2800000 --tx-out addr_test1vpgpgpss8k2r53vus3m3d3j9jvmjc9a8ve836h7pdaff6rc69n7v6+18446744073709551616`: \nE           cardano-cli: out of bounds : 18446744073709551616\nE           CallStack (from HasCallStack):\nE             error, called at src/Shelley/Spec/Ledger/Coin.hs:85:7 in shelley-spec-ledger-0.1.0.0-HfhISpN74MdH4YWGDs1y5I:Shelley.Spec.Ledger.Coin\n\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/clusterlib.py:251: CLIError"}, "description": "Build a transaction with unbalanced change.", "start": 1604494399561, "stop": 1604494400806, "uuid": "ad42540c-8f64-4cce-9c0f-236c29cb3263", "historyId": "02182d8478a1766dae817e118f70e134", "testCaseId": "4a900648fdb6182cd83a0aae471e7dbf", "fullName": "cardano_node_tests.tests.test_transactions.TestNotBalanced#test_wrong_balance", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('temp_dir')"}, {"name": "tag", "value": "hypothesis"}, {"name": "parentSuite", "value": "cardano_node_tests.tests"}, {"name": "suite", "value": "test_transactions"}, {"name": "subSuite", "value": "TestNotBalanced"}, {"name": "host", "value": "bender-3900x"}, {"name": "thread", "value": "19856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cardano_node_tests.tests.test_transactions"}], "links": [{"type": "link", "url": "https://github.com/input-output-hk/cardano-node-tests/blob/d28a503424b5f9f0359a9e79ea272dfac0f801bd/cardano_node_tests/tests/test_transactions.py#L487", "name": "https://github.com/input-output-hk/cardano-node-tests/blob/d28a503424b5f9f0359a9e79ea272dfac0f801bd/cardano_node_tests/tests/test_transactions.py#L487"}]}